### ISSUE TITLE
Version 0.4 not compatible with Python2.7

### ISSUE THREAD

**Issue by Mr-Brewer** [matthew-brett/transforms3d#49]
[Carla-Ros Bridge](https://github.com/carla-simulator/ros-bridge) for ROS1 is leaning quite a bit on the package, until v0.3.1 python2.7 compatibilty was OK, since the recent release of v0.4 `transforms3d` cannot be installed under python2.7. Is this python version supposed to be working? Or is support dropped from v0.4 and onwards?

Installation feedback;
```bash
Going to run the following command:

yes | pip2 install --user transforms3d 

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting transforms3d
  Using cached transforms3d-0.4.tar.gz (1.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v6X2D4/transforms3d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v6X2D4/transforms3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cnpUzW
         cwd: /tmp/pip-install-v6X2D4/transforms3d/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v6X2D4/transforms3d/setup.py", line 8, in <module>
        import versioneer
      File "versioneer.py", line 370
        LONG_VERSION_PY: Dict[str, str] = {}
                       ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by matthew-brett** [comment]
Aha - thanks - I hadn't deliberately broken 2.7 support, no - but it appears that Versioneer did drop support for Python 2.7.  Is it important for you?   I can investigate what it would take to restore it.

**Comment by Mr-Brewer** [comment]
True, it's indeed versioneer that dropped support. We've been working with transforms3d on ros-melodic and the Carla Ros Bridge, so therefore python2.7. So far we've been using v0.3.1 without any problems, so that's also what I'm using now. Just wanted to open this issue to check whether it was deliberately or not. I mean in general python2.7 has reached end of life already, so it makes sense drop compatibility at some time. If it's not too challenging then it might be nice to have 1 more version that supports 2.7. What do you think?

**Comment by matthew-brett** [comment]
My preference would be to drop compatibility at this stage - because Versioneer dropped compatibility some time ago ...  so we'd have to go back a long way in Versioneer versions.   And - 0.4 does have a nice fix for inverse shear calculations - but those are a little uncommon - so 0.3.1 would probably be fine for your uses.

**Comment by MFZ007bin** [comment]
pip install transforms3d==0.3.1

**Comment by matthew-brett** [comment]
I've yanked the 0.4 release, and added a 0.4.1 release that specifies it needs Python 3.6 or above.   This means that `pip install transforms3d` on Python 2.7 will install version 0.3.1 by default.

**Comment by hardesh-peppermint** [comment]
Hi,
With python2, the package is not being installed properly. I had to use `pip install transforms3d==0.3.1` to make the package work with python2

**Comment by Mr-Brewer** [comment]
> I've yanked the 0.4 release, and added a 0.4.1 release that specifies it needs Python 3.6 or above. This means that `pip install transforms3d` on Python 2.7 will install version 0.3.1 by default.

Alright, thanks for the clarification. Closing this issue.
