### ISSUE TITLE
version of `transforms3d` installed via `apt install` is `0.3.1` not the newest one

### ISSUE THREAD

**Issue by ktro2828** [matthew-brett/transforms3d#60]
Hi, I tried to install `transforms3d` via `apt install python3-transforms3d`, but the installed version is `0.3.1` not `0.4.1`(the newest one).

```shell
$ sudo apt-get install python3-transforms3d
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  python3-transforms3d
0 upgraded, 1 newly installed, 0 to remove and 265 not upgraded.
Need to get 42.8 kB of archives.
After this operation, 225 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 python3-transforms3d all 0.3.1+ds-2 [42.8 kB]
Fetched 42.8 kB in 1s (41.2 kB/s)               
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
Selecting previously unselected package python3-transforms3d.
(Reading database ... 193896 files and directories currently installed.)
Preparing to unpack .../python3-transforms3d_0.3.1+ds-2_all.deb ...
Unpacking python3-transforms3d (0.3.1+ds-2) ...
Setting up python3-transforms3d (0.3.1+ds-2) ...
```

Therefore, it makes the following error.
```shell
$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import transforms3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/transforms3d/__init__.py", line 10, in <module>
    from . import quaternions
  File "/usr/lib/python3/dist-packages/transforms3d/quaternions.py", line 26, in <module>
    _MAX_FLOAT = np.maximum_sctype(np.float)
  File "/home/autoware/.local/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?
```

My environment
- Ubuntu 22.04
- Python 3.10.12

**Comment by matthew-brett** [comment]
I'm afraid the version you get with `apt` is the version that the Ubuntu 22.04 packagers built.   I would recommend installing with `pip install transforms3d` instead.

**Comment by ktro2828** [comment]
@matthew-brett Thanks, I got it
